<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Nams-iMac-2.local" name="com.nvg.anibis.testcases.nativeapp.AccountTest" tests="1" failures="1" timestamp="30 Dec 2015 10:40:53 GMT" time="36.504" errors="0">
  <testcase name="validLogInTest" time="36.504" classname="com.nvg.anibis.testcases.nativeapp.AccountTest">
    <failure type="junit.framework.AssertionFailedError" message="Cannot login!">
      <![CDATA[junit.framework.AssertionFailedError: Cannot login!
	at com.nvg.anibis.screens.nativeapp.pagefactory.LoginPage.waitForLogin(LoginPage.java:81)
	at com.nvg.anibis.screens.nativeapp.pagefactory.LoginPage.loginWith(LoginPage.java:68)
	at com.nvg.anibis.screens.nativeapp.pagefactory.LoginPage.validLogin(LoginPage.java:63)
	at com.nvg.anibis.testcases.nativeapp.AccountTest.lambda$0(AccountTest.java:30)
	at com.nvg.anibis.base.nativeapp.TestBase.executeInTryCatch(TestBase.java:49)
	at com.nvg.anibis.testcases.nativeapp.AccountTest.validLogInTest(AccountTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- validLogInTest -->
</testsuite> <!-- com.nvg.anibis.testcases.nativeapp.AccountTest -->
